language: cpp
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libjsoncpp-dev
    - libboost-all-dev
    - libgtest-dev
    - gobjc++
    - gobjc++-multilib
cache:
  directories:
  - lib/
script:
  - cmake . && make

