language: cpp
sudo: false
addons:
  apt:
    packages:
    - libjsoncpp-dev
#    Install arm deps
    - libc6-dev-armhf-cross
    - g++-arm-linux-gnueabihf
cache:
  directories:
  - lib/
script:
  - cmake . && make
