language: cpp
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libjsoncpp-dev
    - gobjc++
    - gobjc++-4.9
    - gobjc++-4.9-multilib
cache:
  directories:
  - lib/
script:
  - cmake . && make

