language: cpp
sudo: required
dist: precise
addons:
  apt:
    packages:
    - libasound2-dev                                                                
    - libexpat1-dev
    - libgconf2-dev
    - libgnome-keyring-dev
    - libgtk2.0-dev
    - libjpeg62-dev
    - libnss3-dev
    - libpci-dev
    - libpulse-dev
    - libudev-dev
    - libxss-dev
    - libxtst-dev
    - libxv-dev
cache:
  directories:
  - lib/webrtc
env:
  - GYP_CROSSCOMPILE=1 GYP_DEFINES="OS=linux target_arch=arm"
before_install:
  - unset CC
  - unset CXX
install:
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH=`pwd`/depot_tools:"$PATH"
  - cd lib/webrtc
  - if [ ! -d "src" ]; then fetch --no-history --nohooks webrtc; fi
  - gclient sync
before_script:
  - cd $TRAVIS_BUILD_DIR
script:
  - ninja -C lib/webrtc/src/out/Release
  - cmake . && make
