language: cpp
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
#    - g++-4.9-arm-linux-gnueabi
    - g++-4.9-multilib
env:
  - ARCH=amd64 CMAKE_CC=gcc-4.9 CMAKE_CXX=g++-4.9
#  - ARCH=arm CC=arm-linux-gnueabihf-gcc-4.9 CXX=arm-linux-gnueabihf-g++-4.9
cache:
  directories:
  - lib/
install:
  - wget -nc https://ci-cloud.s3-eu-west-1.amazonaws.com/webrtc/libwebrtc-Linux-$ARCH-r49.a -P lib/
script:
  - cmake . -DARCH=$ARCH -DCMAKE_CXX_COMPILER=$CMAKE_CXX -DCMAKE_C_COMPILER=$CMAKE_CC
  - make

