language: cpp
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libboost-all-dev
env:
#  - ARCH=amd64
  - ARCH=arm
cache:
  directories:
  - lib/
install:
  - wget https://ci-cloud.s3-eu-west-1.amazonaws.com/webrtc/libwebrtc-Linux-$ARCH-r49.a -P lib/
script:
  - cmake .
  - make

