---
version: 1
signaling_servers:
- ws://10.20.30.20:8000/ws/device/test/
i2c_bus:
  motor: 2
  sensor: 1
motors: {}
sensors:
  left_mtp:
    address: 22
    mode: 1
    registry: 1
    mirror: y
    rows: 10
    cols: 16
    zero_value: 0
    half_value: 2047
    full_value: 4095
  left_hallux:
    address: 22
    mode: 1
    registry: 2
    mirror: y
    rows: 12
    cols: 6
    zero_value: 0
    half_value: 2047
    full_value: 4095
