---
version: 1
signaling_servers:
- ws://10.20.30.20:8000/ws/device/test/
i2c_bus:
  motor: 2
  sensor: 1
motors:
  right_first_ray:
     address: 0x08
     cal: 700
     low: 450
     high: 0
     speed: 50
     damping: 127
     control: 1
#  right_foot_size:
#    address: 0x20
#    cal: -20
#    low: 0
#    high: 126000
#    speed: 255
#    damping: 127
#    control: 7
#  right_rear_tilt:
#    address: 0x21
#    cal: -260
#    low: -240
#    high: 240
#    speed: 100
#    damping: 127
#    control: 5
sensors:
#  left_heel:
#    address: 0x16
#    mode: 2
#    registry: 1
#    mirror: n
#    rows: 12
#    cols: 12
#    zero_value: 0
#    half_value: 2047
#    full_value: 4095
  left_mtp:
    address: 0x16 #temp
    mode: 1
    registry: 1
    mirror: y
    rows: 10
    cols: 16
    zero_value: 0
    half_value: 2047
    full_value: 4095
#  right_heel:
#    address: 0x25
#    mode: 2
#    registry: 1
#    mirror: n
#    rows: 12
#    cols: 12
#    zero_value: 0
#    half_value: 2047
#    full_value: 4095
#  right_mtp:
#    address: 0x26
#    mode: 1
#    registry: 1
#    mirror: y
#    rows: 10
#    cols: 16
#    zero_value: 0
#    half_value: 2047
#    full_value: 4095
#  right_hallux:
#    address: 0x26
#    mode: 1
#    registry: 2
#    mirror: y
#    rows: 12
#    cols: 6
#    zero_value: 0
#    half_value: 2047
#    full_value: 4095
